#!/bin/bash

. `dirname $0`/lib/util

for checksum in `ls $ARTIFACTS_DIR`; do
  if [ -d $ARTIFACTS_DIR/$checksum ]; then
    filename=`cat $ARTIFACTS_DIR/$checksum/filename`
    echo "$checksum: $filename"
  fi
done
