#!/bin/bash

# make sure there is a previous deployment
previous_deployment=`ls ~/app-root/runtime/deployments | sort | tail -2 | sed -e '$ d'`
if [ "x$previous_deployment" == "x" ]; then
  echo "No previous deployment exists"
  exit 1
fi
