#!/bin/bash

. `dirname $0`/lib/util

# make sure there is a previous deployment
previous_deployment=`ls $DEPLOYMENTS_DIR | sort | tail -2 | sed -e '$ d'`
if [ "x$previous_deployment" == "x" ]; then
  echo "No previous deployment exists"
  exit 1
fi
