#!/bin/bash

for f in `ls ~/app-root/runtime/deployments | sort`; do
  checksum=`cat ~/app-root/runtime/deployments/$f/checksum`
  filename=`cat ~/app-root/runtime/artifacts/$checksum/filename`
  echo "$f - $checksum - $filename"
done
