#!/bin/bash

. `dirname $0`/lib/util

for f in `ls $DEPLOYMENTS_DIR | sort`; do
  checksum=`cat $DEPLOYMENTS_DIR/$f/checksum`
  filename=`cat $ARTIFACTS_DIR/$checksum/filename`
  echo "$f - $checksum - $filename"
done
