#!/bin/bash

# args
# 1 - deployment id (YYYYmmddHHMMSS)
# 2 - checksum of artifact to be deployed

. `dirname $0`/lib/util

deployment_id=$1
checksum=$2

deployment_dir=$DEPLOYMENTS_DIR/$deployment_id
repo_dir=$deployment_dir/repo

if [ ! -e $repo_dir ]; then
  mkdir -p $repo_dir

  cd $repo_dir

  tar xf $ARTIFACTS_DIR/$checksum/$checksum

  echo $checksum > $deployment_dir/checksum
fi
