#!/bin/bash

# Import Environment Variables
for f in ~/.env/*; do
  . $f
done

script_dir=`dirname $0`

# call the user specific prepare, which must download the artifact and echo its location
echo "Executing user_prepare"
artifact_and_sha1=`$script_dir/user_prepare "$@"`

if [ $? -ne 0 ]; then
  echo "Error running user_prepare: $artifact_and_sha1"
  exit 1
fi

echo "Result: $artifact_and_sha1"

# will be something like /tmp/foo.tgz
tmp_artifact=`echo $artifact_and_sha1 | cut -f 1 -d ' '`

# just the sha
artifact_sha1=`echo $artifact_and_sha1 | cut -f 2 -d ' '`

# will turn /tmp/foo.tgz into foo.tgz
artifact_name=`basename $tmp_artifact`

# move the artifact to the artifacts dir
artifact_dir=$OPENSHIFT_HOMEDIR/app-root/runtime/artifacts/$artifact_sha1

echo "Creating directory $artifact_dir"
mkdir -p $artifact_dir

echo "Moving $tmp_artifact to $artifact_dir"
mv $tmp_artifact $artifact_dir/$artifact_sha1

echo "Writing '$artifact_name' to $artifact_dir/filename"
echo $artifact_name > $artifact_dir/filename

echo "Use the following identifier when distributing and activating this artifact: $artifact_sha1"
