#!/bin/bash

# Import Environment Variables
for f in ~/.env/*; do
  . $f
done

. /usr/libexec/openshift/cartridges/abstract/info/lib/util

script_dir=`dirname $0`

if $script_dir/can_rollback; then
  previous_deployment=`ls ~/app-root/runtime/deployments | sort | tail -2 | sed -e '$ d'`

  echo "Stopping application"
  stop_app

  current_repo=`readlink ~/app-root/runtime/repo`
  current_deployment=`dirname $current_repo`

  echo "Deleting current repo symlink"
  rm ~/app-root/runtime/repo

  echo "Deleting current deployment"
  rm -rf $current_deployment

  deployment_repo_dir=$OPENSHIFT_HOMEDIR/app-root/runtime/deployments/$previous_deployment/repo

  echo "Linking $deployment_repo_dir to ~/app-root/runtime/repo"
  ln -s $deployment_repo_dir ~/app-root/runtime/repo

  java_artifacts=`find $deployment_repo_dir -iname \*.war -o -iname \*.ear -o -iname \*.sar | wc -l`
  if [ $java_artifacts -ne 0 ] && [ -e $deployment_repo_dir/deployments ] && [ ! -e $deployment_repo_dir/deployments/ROOT.war ]; then
    cp ~/app-root/runtime/scripts/ROOT.war $deployment_repo_dir/deployments/ROOT.war
  fi

  set_app_state deploying

  framework_carts=($(get_installed_framework_carts))
  primary_framework_cart=${framework_carts[0]}

  echo "Calling deploy"
  if [ -e ${CARTRIDGE_BASE_PATH}/${primary_framework_cart}/info/bin/deploy.sh ]; then
    ${CARTRIDGE_BASE_PATH}/${primary_framework_cart}/info/bin/deploy.sh
  else
    ${CARTRIDGE_BASE_PATH}/abstract/info/bin/deploy.sh
  fi

  echo "Starting application"
  start_app
  
  echo "Calling post_deploy"
  if [ -e ${CARTRIDGE_BASE_PATH}/${primary_framework_cart}/info/bin/post_deploy.sh ]; then
    ${CARTRIDGE_BASE_PATH}/${primary_framework_cart}/info/bin/post_deploy.sh
  else
    ${CARTRIDGE_BASE_PATH}/abstract/info/bin/post_deploy.sh
  fi
else
  echo "can_rollback returned nonzero exit - unable to rollback"
  exit 1
fi
