#!/bin/bash

. `dirname $0`/lib/util

. /usr/libexec/openshift/cartridges/abstract/info/lib/util

script_dir=`dirname $0`

# OPENSHIFT_REPO_DIR ends with /, need to remove it when renaming
# hence the %?
REPO_DIR=${OPENSHIFT_REPO_DIR%?}

if $script_dir/can_rollback; then
  previous_deployment=`ls $DEPLOYMENTS_DIR | sort | tail -2 | sed -e '$ d'`

  echo "Stopping application"
  stop_app

  current_repo=`readlink $REPO_DIR`
  current_deployment=`dirname $current_repo`

  echo "Deleting current repo symlink"
  rm $REPO_DIR

  echo "Deleting current deployment"
  rm -rf $current_deployment

  deployment_repo_dir=$DEPLOYMENTS_DIR/$previous_deployment/repo

  echo "Linking $deployment_repo_dir to $REPO_DIR"
  ln -s $deployment_repo_dir $REPO_DIR

  java_artifacts=`find $deployment_repo_dir -iname \*.war -o -iname \*.ear -o -iname \*.sar | wc -l`
  if [ $java_artifacts -ne 0 ] && [ -e $deployment_repo_dir/deployments ] && [ ! -e $deployment_repo_dir/deployments/ROOT.war ]; then
    cp $SCRIPTS_DIR/ROOT.war $deployment_repo_dir/deployments/ROOT.war
  fi

  set_app_state deploying

  framework_carts=($(get_installed_framework_carts))
  primary_framework_cart=${framework_carts[0]}

  echo "Calling deploy"
  if [ -e ${CARTRIDGE_BASE_PATH}/${primary_framework_cart}/info/bin/deploy.sh ]; then
    ${CARTRIDGE_BASE_PATH}/${primary_framework_cart}/info/bin/deploy.sh
  else
    ${CARTRIDGE_BASE_PATH}/abstract/info/bin/deploy.sh
  fi

  echo "Starting application"
  start_app
  
  echo "Calling post_deploy"
  if [ -e ${CARTRIDGE_BASE_PATH}/${primary_framework_cart}/info/bin/post_deploy.sh ]; then
    ${CARTRIDGE_BASE_PATH}/${primary_framework_cart}/info/bin/post_deploy.sh
  else
    ${CARTRIDGE_BASE_PATH}/abstract/info/bin/post_deploy.sh
  fi
else
  echo "can_rollback returned nonzero exit - unable to rollback"
  exit 1
fi
