#!/bin/bash

. `dirname $0`/lib/util

# OPENSHIFT_REPO_DIR ends with /, need to remove it when renaming
# hence the %?
REPO_DIR=${OPENSHIFT_REPO_DIR%?}

if [ -L $REPO_DIR ]; then
  checksum=`cat $REPO_DIR/../checksum`
  filename=`cat $ARTIFACTS_DIR/$checksum/filename`

  valid='OK'
  `$SCRIPTS_DIR/validate $checksum`
  if [ $? -ne 0 ]; then
    valid='NOT OK'
  fi

  echo "$filename ($checksum: $valid)"
else
  echo 'Unknown; deployment not activated using binary deployment process'
fi
